# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MyMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(660, 10, 291, 421))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.activityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.activityLabel.setObjectName("activityLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.activityLabel)
        self.activityComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.activityComboBox.setObjectName("activityComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activityComboBox)
        self.stateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setMaxVisibleItems(30)
        self.stateComboBox.setObjectName("stateComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stateComboBox)
        self.cityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cityLabel)
        self.cityComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cityComboBox.setMaxVisibleItems(30)
        self.cityComboBox.setObjectName("cityComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cityComboBox)
        self.radiusLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.radiusLineEdit.setCursorPosition(0)
        self.radiusLineEdit.setObjectName("radiusLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radiusLineEdit)
        self.radiusLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activityLabel.setText(_translate("MainWindow", "Select an Activity:"))
        self.stateLabel.setText(_translate("MainWindow", "Select a State:"))
        self.cityLabel.setText(_translate("MainWindow", "Select a City:"))
        self.radiusLineEdit.setInputMask(_translate("MainWindow", "D9000"))
        self.radiusLabel.setText(_translate("MainWindow", "Type a Radius (mi):"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionClear.setText(_translate("MainWindow", "Clear Form"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear All Entries"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit Application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionInstructions.setToolTip(_translate("MainWindow", "Gives instructions on how to use the application"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setToolTip(_translate("MainWindow", "Opens preferences menu to change server settings"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+Alt+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

