# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MyMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(660, 10, 291, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.activityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.activityLabel.setObjectName("activityLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.activityLabel)
        self.activityComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.activityComboBox.setObjectName("activityComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activityComboBox)
        self.stateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stateLabel)
        self.stateComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.stateComboBox.setMaxVisibleItems(30)
        self.stateComboBox.setObjectName("stateComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stateComboBox)
        self.cityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.cityLabel.setObjectName("cityLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cityLineEdit)
        self.radiusLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        self.searchButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.searchButton)
        self.radiusComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.radiusComboBox.setMaxVisibleItems(30)
        self.radiusComboBox.setObjectName("radiusComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radiusComboBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tempLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.tempLabel.setMaximumSize(QtCore.QSize(16777215, 160))
        self.tempLabel.setText("")
        self.tempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.verticalLayout_2.addWidget(self.tempLabel)
        self.tempStatLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.tempStatLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tempStatLabel.setText("")
        self.tempStatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempStatLabel.setObjectName("tempStatLabel")
        self.verticalLayout_2.addWidget(self.tempStatLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.windLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.windLabel.setMaximumSize(QtCore.QSize(16777215, 160))
        self.windLabel.setText("")
        self.windLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.windLabel.setObjectName("windLabel")
        self.verticalLayout_4.addWidget(self.windLabel)
        self.windStatLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.windStatLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.windStatLabel.setText("")
        self.windStatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.windStatLabel.setObjectName("windStatLabel")
        self.verticalLayout_4.addWidget(self.windStatLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cloudsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cloudsLabel.setMaximumSize(QtCore.QSize(16777215, 160))
        self.cloudsLabel.setText("")
        self.cloudsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cloudsLabel.setObjectName("cloudsLabel")
        self.verticalLayout.addWidget(self.cloudsLabel)
        self.cloudsStatLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cloudsStatLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cloudsStatLabel.setText("")
        self.cloudsStatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cloudsStatLabel.setObjectName("cloudsStatLabel")
        self.verticalLayout.addWidget(self.cloudsStatLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.rainLabel = QtWidgets.QLabel(self.centralwidget)
        self.rainLabel.setGeometry(QtCore.QRect(843, 150, 111, 91))
        self.rainLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.rainLabel.setText("")
        self.rainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rainLabel.setObjectName("rainLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 230, 931, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 929, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.printLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.printLabel.setFont(font)
        self.printLabel.setAutoFillBackground(False)
        self.printLabel.setText("")
        self.printLabel.setTextFormat(QtCore.Qt.RichText)
        self.printLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.printLabel.setContentsMargins(15, 15, 15, 15)
        self.printLabel.setOpenExternalLinks(True)
        self.printLabel.setObjectName("printLabel")
        self.verticalLayout_3.addWidget(self.printLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activityLabel.setText(_translate("MainWindow", "Select an Activity:"))
        self.stateLabel.setText(_translate("MainWindow", "Select a State:"))
        self.cityLabel.setText(_translate("MainWindow", "Type a City:"))
        self.radiusLabel.setText(_translate("MainWindow", "Type a Radius (mi):"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionClear.setText(_translate("MainWindow", "Clear Form"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear All Entries"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit Application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionInstructions.setToolTip(_translate("MainWindow", "Gives instructions on how to use the application"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setToolTip(_translate("MainWindow", "Opens preferences menu to change server settings"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+Alt+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

